# Services for Solakon ONE integration

refresh_data:
  name: Refresh Data
  description: Manually refresh all sensor data from the Solakon ONE device
  fields: {}

set_battery_charge_limit:
  name: Set Battery Charge Limit
  description: Set the maximum charge percentage for the battery
  fields:
    limit:
      name: Charge Limit
      description: Maximum battery charge percentage (0-100)
      required: true
      example: 90
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"

set_battery_discharge_limit:
  name: Set Battery Discharge Limit
  description: Set the minimum discharge percentage for the battery
  fields:
    limit:
      name: Discharge Limit
      description: Minimum battery discharge percentage (0-100)
      required: true
      example: 10
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"

set_work_mode:
  name: Set Work Mode
  description: Set the inverter work mode
  fields:
    mode:
      name: Work Mode
      description: The work mode to set
      required: true
      example: "self_use"
      selector:
        select:
          options:
            - "self_use"
            - "feed_in_priority"
            - "backup"
            - "force_charge"

set_time_of_use:
  name: Set Time of Use
  description: Configure time-of-use charging/discharging schedules
  fields:
    period:
      name: Period
      description: Time period number (1-6)
      required: true
      example: 1
      selector:
        number:
          min: 1
          max: 6
    enabled:
      name: Enabled
      description: Enable or disable this time period
      required: true
      example: true
      selector:
        boolean:
    start_time:
      name: Start Time
      description: Start time for the period (HH:MM)
      required: false
      example: "00:00"
      selector:
        time:
    end_time:
      name: End Time
      description: End time for the period (HH:MM)
      required: false
      example: "06:00"
      selector:
        time:
    charge_enabled:
      name: Charge Enabled
      description: Enable charging during this period
      required: false
      example: true
      selector:
        boolean:
    discharge_enabled:
      name: Discharge Enabled
      description: Enable discharging during this period
      required: false
      example: false
      selector:
        boolean: